#!/usr/bin/env python3

import subprocess
from pathlib import Path
import time

card = '/proc/asound/card1/stream0'

flag_path = Path(flag_file)

completed_process  = subprocess.run(["grep", "-i", "Status: Running", card], returncode=1)
if completed_process == 0:
    echo "Playing"
    flag_path.touch()
else:
    try:
        # get ctime
        ctime = flag_path.stat().st_ctime
    except FileNotFoundError:
        #print("Flag file not found. Creating ", flag_file)
        flag_path.touch()
    else:
        if ctime < time.time() - shutdown_delay_min * 60:
            print("Shutting down PortPi")
            flag_path.unlink()
            subprocess.run(['/sbin/shutdown','-P','now'])
